enable_damage = true
creative_mode = true
mainmenu_last_selected_world = 1
maintab_LAST = local
menu_last_game = minetest
free_move = true
fast_move = false
mute_sound = true
fullscreen = true
noclip = false
